### ISSUE TITLE
05-utrdimo-osnove lahko odpremo le iz uvodne strani učbenika

### ISSUE THREAD

**Issue by Kajaaa9** [katjabercic/racunalniski-praktikum#19]
Razdelek Utrdimo osnove (05-utrdimo-osnove) je v kazalu viden le, če smo na uvodni strani (00-uvod). Če najprej odpremo npr. Urejevalnik in ukazna vrstica (ali kater koli drug naslov v kazalu) potem v kazalu ni več prikazanega razdelka Utrdimo osnove.

Prav tako lahko do razdelka 06-uvod-v-latex pridemo le če na povezavo zanj kliknemo v domači nalogi na dnu strani 05-utrdimo-osnove, saj v kazalu ni viden.

**Comment by Kajaaa9** [comment]
Če imamo odprt naslov Plonkec za ukazno vrstico (C-ukazna-vrstica) ali Pisanje e-pošte profesorjem in asistentom (E-posta) v kazalu prav tako ni vidnega naslova Oblikovanje HTML dokumentov s CSS (04-css).

**Comment by katjabercic** [comment]
Hvala za opozorilo! Zdaj bi moralo biti ok.
Razdelek 06-uvod-v-latex pa še ni mišljen, da bi bil viden, ker še ni pripravljen.
